/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/helmet/HockeyHelmet.glb");

  const [hover, setHover] = useState(false);

  const handleHover = () => {};

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        geometry={nodes.Binding_1.geometry}
        material={materials.Plastik_001}
        position={[0, 0.02, 0.07]}
      />
      <mesh
        castShadow
        geometry={nodes.Binding_2.geometry}
        material={materials.Plastik_001}
        position={[0, -0.09, -0.12]}
      />
      <mesh
        castShadow
        geometry={nodes.Rivet_1.geometry}
        material={materials.Helmet_001}
        position={[-0.1, -0.07, 0.03]}
      />
      <mesh
        castShadow
        geometry={nodes.Rivet_2.geometry}
        material={materials.Helmet_001}
        position={[-0.1, -0.1, 0.03]}
      />
      <mesh
        castShadow
        geometry={nodes.Rivet_3.geometry}
        material={materials.Helmet_001}
        position={[-0.1, -0.11, -0.02]}
      />
      <mesh
        castShadow
        geometry={nodes.Rivet_4.geometry}
        material={materials.Chrome_001_SMR}
        position={[-0.1, -0.1, -0.04]}
        scale={0.8}
      />
      <mesh
        castShadow
        geometry={nodes.Rivet_5.geometry}
        material={materials.Chrome_001_SMR}
        position={[-0.1, -0.09, 0.01]}
        scale={0.8}
      />
      <mesh
        castShadow
        geometry={nodes.Tube_1.geometry}
        material={materials.Plastic_Trasparent}
        position={[-0.05, 0.023, 0.075]}
      />
      <mesh
        castShadow
        geometry={nodes.Tube_2.geometry}
        material={materials.Plastic_Trasparent}
        position={[-0.11, -0.05, 0.02]}
      />
      <mesh
        castShadow
        geometry={nodes["Rivet_1-1"].geometry}
        material={materials.Helmet_001}
        position={[0.1, -0.07, 0.03]}
      />
      <mesh
        castShadow
        geometry={nodes["Rivet_5-1"].geometry}
        material={materials.Chrome_001_SMR}
        position={[0.1, -0.09, 0.01]}
        scale={0.8}
      />
      <mesh
        castShadow
        geometry={nodes["Rivet_2-1"].geometry}
        material={materials.Helmet_001}
        position={[0.1, -0.1, 0.03]}
      />
      <mesh
        castShadow
        geometry={nodes["Rivet_3-1"].geometry}
        material={materials.Helmet_001}
        position={[0.1, -0.11, -0.02]}
      />
      <mesh
        castShadow
        geometry={nodes["Rivet_4-1"].geometry}
        material={materials.Chrome_001_SMR}
        position={[0.1, -0.1, -0.04]}
        scale={0.8}
      />
      <mesh
        castShadow
        geometry={nodes["Tube_2-1"].geometry}
        material={materials.Plastic_Trasparent}
        position={[0.11, -0.05, 0.02]}
      />
      <mesh
        castShadow
        geometry={nodes["Tube_1-1"].geometry}
        material={materials.Plastic_Trasparent}
        position={[0.05, 0.023, 0.075]}
      />
      <mesh
        castShadow
        geometry={nodes.Pad.geometry}
        material={materials.Plastik_001}
        position={[0, -0.01, -0.04]}
      />
      <mesh
        castShadow
        geometry={nodes.Mask.geometry}
        material={materials.Chrome}
        position={[0, -0.05, 0.07]}
        material-color="red"
      />
      <mesh
        castShadow
        onPointerEnter={() => setHover(true)}
        onPointerLeave={() => setHover(false)}
        geometry={nodes.Helmet.geometry}
        material={materials.Helmet_001}
        position={[0, -0.01, -0.03]}
        material-color={hover ? "red" : "skyblue"}
      ></mesh>
      <mesh
        castShadow
        geometry={nodes.Screw_003.geometry}
        material={materials.Chrome_001_SMR}
        position={[-0.05, 0.03, 0.07]}
        scale={0.8}
      />
      <mesh
        castShadow
        geometry={nodes.Screw_004.geometry}
        material={materials.Chrome_001_SMR}
        position={[-0.11, -0.05, 0.03]}
        scale={0.8}
      />
      <mesh
        castShadow
        geometry={nodes["Screw_2-002"].geometry}
        material={materials.Chrome_001_SMR}
        position={[0.11, -0.05, 0.03]}
        scale={0.8}
      />
      <mesh
        castShadow
        geometry={nodes["Screw_1-002"].geometry}
        material={materials.Chrome_001_SMR}
        position={[0.05, 0.03, 0.07]}
        scale={0.8}
      />
      <mesh
        castShadow
        geometry={nodes.Helmet_TrimSheet.geometry}
        material={materials["Helmet_001.001"]}
        position={[0, -0.01, -0.03]}
        material-color="green"
      />
    </group>
  );
}

useGLTF.preload("/models/helmet/HockeyHelmet.glb");
